_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.999
checkpoint_path:
    value: checkpoints/transformer_lm.ckpt
context_length:
    value: 256
cosine_cycle_iters:
    value: 8000
d_ff:
    value: 1344
d_model:
    value: 512
device:
    value: cpu
eps:
    value: "1e-8"
log_interval:
    value: 100
max_grad_norm:
    value: 1
max_iters:
    value: 5
max_lr:
    value: 0.001
min_lr:
    value: 1e-05
n_layers:
    value: 1
num_heads:
    value: 4
optimizer:
    value: adamw
save_interval:
    value: 1000
train_data:
    value: data/train_tokens.npy
val_data:
    value: data/val_tokens.npy
val_interval:
    value: 500
vocab_size:
    value: 10000
warmup_iters:
    value: 500
weight_decay:
    value: 0.01
